package ExceptionHandling;
public class ExceptionTest8 {
    public static void main(String[] args) {
        try {
            throw new Exception();
        } catch (Exception e) {
           
        	System.out.println(e);
        }
        System.out.println("No exception occurred.");
    }
}
