package ExceptionHandling;
public class ExceptionTest8 {
    public static void main(String[] args) throws Exception {
        try {
           
        } catch (Exception e) {
           
        	 throw new Exception();
        }
        System.out.println("No exception occurred.");
    }
}
